import RestaurantNavBar from "../components/RestaurantNavBar";
import Menu from "../components/Menu";
import { PrismaClient } from "@prisma/client";

export const metadata = {
  title: 'Menu to the restaurant - OpenTable',
  description: 'Generated by create next app',
}

const prisma = new PrismaClient();
const fecthRestaurantMenu = async (slug: string) => {
  const restaurant = await prisma.restaurant.findUnique({
    where: {
      slug
    },
    select: {
      items: true,
    }
  })
  if(!restaurant) throw new Error();

  return restaurant.items;
}

export default async function RestaurantMenu({params}: {params: {slug: string}}) {

    const menu = await fecthRestaurantMenu(params.slug);

    return (
            <div className="bg-white w-[100%] rounded shadow p-3">
              <RestaurantNavBar slug={params.slug}/>
              <Menu menu={menu} />
            </div>  
    )
}